name: Backend CI

on:
  push:
    paths:
      - "Backend/**"
  pull_request:
    paths:
      - "Backend/**"

jobs:
  node-server:
    name: Node.js Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Node.js dependencies
        run: npm install
        working-directory: Backend

      - name: Lint/Start/Build Node.js
        run: |
          echo "Node.js server test (replace with real tests or start script)"
          npm start || echo "No tests configured"
        working-directory: Backend

  flask-model:
    name: Flask API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt"
        working-directory: Backend

      - name: Run Flask test or check
        run: |
          echo "Flask ready (skip running actual server in CI)"
        working-directory: Backend
